apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mf6p5tq43-go
  janus-idp.io/tekton: mf6p5tq43-go
  backstage.io/kubernetes-id: mf6p5tq43-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mf6p5tq43-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
