apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mf6p5tq43-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mf6p5tq43-go 
  name: mf6p5tq43-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mf6p5tq43-go 
